/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
export const projectId = "yejjhcrhbsrfvriojqzb";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllampoY3JoYnNyZnZyaW9qcXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMTg3MjIsImV4cCI6MjA4Mzg5NDcyMn0.96F3nQ2mUQoR--jC9MR-eXuAiOE7v1yVM8Mc-lXld_s";
