import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function SobreMiSection({ isZoomed = false, onNavigate }) {
    const handleClick = () => {
        if (isZoomed && onNavigate) {
            onNavigate('sobre-mi');
        }
    };
    return (_jsx("div", { className: "relative w-full h-full bg-[#f7f2ed] flex items-center justify-center p-4 md:p-8 lg:p-0", children: _jsx("div", { className: `w-full max-w-[388px] lg:absolute lg:top-[38px] lg:right-[38px] ${isZoomed ? 'cursor-pointer hover:scale-105 transition-transform duration-300' : ''}`, onClick: handleClick, children: _jsx("div", { className: "w-full min-h-[400px] max-h-[584px] lg:h-[584px] bg-[#e8d8c9] rounded-[22px] border-2 border-[#5a3e26] border-dashed shadow-[25px_25px_10px_0px_rgba(0,0,0,0),16px_16px_9px_0px_rgba(0,0,0,0.02),9px_9px_8px_0px_rgba(0,0,0,0.07),4px_4px_6px_0px_rgba(0,0,0,0.12),1px_1px_3px_0px_rgba(0,0,0,0.14)]", children: _jsx("div", { className: "p-6 md:p-8 lg:p-[48px] lg:px-[32px] overflow-auto h-full", children: _jsxs("p", { className: "font-['Roboto:Regular',sans-serif] text-sm md:text-base lg:text-[14px] text-black text-justify leading-[1.2]", children: ["Hola, soy Francisco S\u00E1nchez, arquitecto de profesi\u00F3n con una experiencia laboral de m\u00E1s de 14 a\u00F1os, dise\u00F1ando y gestionando proyectos de edificaci\u00F3n de diversa tipolog\u00EDa.", _jsx("br", {}), _jsx("br", {}), "Mi camino hacia el UX/UI surge desde mis primeros a\u00F1os de universidad, interes\u00E1ndome en el mundo digital a trav\u00E9s del dise\u00F1o de sitios web, apreci\u00E1ndolos como experiencias habitables digitales.", _jsx("br", {}), _jsx("br", {}), "Posteriormente, al especializarme en BIM, pude darle continuidad a esta inquietud de conocimiento y creatividad, abordando proyectos con una mayor complejidad en la gesti\u00F3n digital de la informaci\u00F3n.", _jsx("br", {}), _jsx("br", {}), "Este cambio de rumbo aparente, es parte sustancial de mi b\u00FAsqueda profesional, ahora en una fase de consolidar mi inter\u00E9s en la creaci\u00F3n de productos digitales, donde quiero volcar mis a\u00F1os de madurez, descubrimientos de trabajar con muchos equipos y aprendizajes que nunca acaban y siempre suman."] }) }) }) }) }));
}
